### ISSUE TITLE
Tutorial 01 doesnt work

### ISSUE THREAD

**Issue by namoscagnm** [BradWBeer/clinch#114]
When typing (clinch:init), I get the error:

SDL Error (#<SDL-GLCONTEXT {#X00000000}>): Could not create GL context
   [Condition of type SDL2::SDL-RC-ERROR]

Backtrace:
  0: (SDL2:GL-CREATE-CONTEXT #<SDL2-FFI:SDL-WINDOW {#X7FFFDC185880}>)
  1: ((LAMBDA NIL :IN CLINCH::_INIT))
  2: ((LAMBDA NIL :IN CLINCH::_INIT))
  3: (SDL2::HANDLE-MESSAGE (#<CLOSURE (LAMBDA NIL :IN CLINCH::_INIT) {100803812B}>))
  4: (SDL2::SDL-MAIN-THREAD)
  5: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
  6: ((FLET #:WITHOUT-INTERRUPTS-BODY-1160 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  7: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  8: ((FLET #:WITHOUT-INTERRUPTS-BODY-359 :IN SB-THREAD::CALL-WITH-MUTEX))
  9: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFE0ECED5B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 10: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Main Clinch Thread" RUNNING {1007E1CCA3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1007E1CC2B}> (#<..
 11: ("foreign function: call_into_lisp")
 12: ("foreign function: new_thread_trampoline")

My system is:
Lubuntu 16.10, using SBCL 1.3.3 on Slime/Emacs. According to the init from Clinch, my SDL version is:
#<SB-THREAD:THREAD "Main Clinch Thread" RUNNING {1007E1CCA3}>
Using SDL Library Version: 2.0.4
Opening game controllers. 44 
Controlers found: NIL

**Comment by namoscagnm** [comment]
A similar problem also happens with Tutorial 02

**Comment by bpanthi977** [comment]
I am also having this problem with both Tutorial 01 and 02.

**Comment by BradWBeer** [comment]
Can you try the latest version from master? Quicklisp hasn't been updated
for a while.

**Comment by bpanthi977** [comment]
Sorry to be late. I cloned the repo and tried it.  Still the tutorials
don't work and I get the same error.

**Comment by BradWBeer** [comment]
I think I fixed this and it works on sever similar systems. I'll call this closed but I can reopen it if it pops up again.
