### ISSUE TITLE
Does not build today - duplicate definition

### ISSUE THREAD

**Issue by quicklisp** [BradWBeer/clinch#123]
Clinch has a duplicate definition:

    ; caught WARNING:
    ;   Duplicate definition for GET-GENERIC-SINGLE-COLOR-SHADER found in one file.
    ;   See also:
    ;     The ANSI Standard, Section 3.2.2.3

This breaks the build on SBCL.

**Comment by BradWBeer** [comment]
Redundantcy removed. Builds using: 

`(ql:quickload :clinch :verbose t)`
