### ISSUE TITLE
Illegal :UTF-8 character starting at position 0

### ISSUE THREAD

**Issue by AyeGill** [BradWBeer/CLinch#28]
When trying to run either of the examples, I get the following error:

    "Compiling vertex shader..." 
    debugger invoked on a BABEL-ENCODINGS:INVALID-UTF8-CONTINUATION-BYTE   in thread
    #<THREAD "main thread" RUNNING {1002978D73}>:
      Illegal :UTF-8 character starting at position 0.

    Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

    restarts (invokable by number or by possibly-abbreviated name):
       0: [ABORT] Exit debugger, returning to top level.

    ((LABELS BABEL-ENCODINGS::UTF-8-DECODER :IN "/home/ayegill/quicklisp/dists/quicklisp/software/cffi_0.10.7.1/src/strings.lisp") #<unavailable lambda list>)
    0] 

Leaving the vertex shader as an empty string lets the execution continue until it hits an identical error on compiling the fragment shader. Leaving both empty avoids the error altogether, but for obvious reasons, compiling the fragment shader fails.

**Comment by BradWBeer** [comment]
I'm closing this issue until I can find it.
