### ISSUE TITLE
DSL for shaders

### ISSUE THREAD

**Issue by smithzvk** [BradWBeer/CLinch#34]
The CEPL project has a DSL for shaders.  It seems like it would be a pretty useful option (though perhaps only an option because it is nice to be able to copy and paste shader code into your program).

Any ideas on implementing something like this, or even better, simpling stealing this functionality from their project?

Their stuff is [L]LGPL, so it would infect the license of CLinch if it is more permissive, but I'm fine with LGPL.  What is the license on CLinch?

**Comment by BradWBeer** [comment]
Since CEPL does this, I'm not going to. Maybe we can collaborate or just plain steal.
