### ISSUE TITLE
Does not build - implicit SWANK dependency

### ISSUE THREAD

**Issue by quicklisp** [BradWBeer/CLinch#45]
I get a failure today with this message:

    READ error during COMPILE-FILE: Package SWANK does not exist

https://github.com/BradWBeer/CLinch/blob/master/clinch.lisp#L53 refers to swank, but swank isn't in the :depends-on list of the system.

**Comment by quicklisp** [comment]
More context here: http://report.quicklisp.org/2015-04-27/failure-report/clinch.html#clinch

**Comment by BradWBeer** [comment]
I removed the offending function. I don't think clinch should rely on 
swank. Thanks for for your patience.

**Comment by quicklisp** [comment]
No problem. Just one more thing...

    ; caught WARNING:                                                                                                                    
    ;   Duplicate definition for MASS-SET-CYLINDER-TOTAL found in  one file.                                                             
    ;   See also:                                                                                                                        
    ;     The ANSI Standard, Section 3.2.2.3

**Comment by quicklisp** [comment]
That's from clode/bindings.lisp.

**Comment by BradWBeer** [comment]
I'll fix it as soon as I get home.

**Comment by BradWBeer** [comment]
Fixed.

**Comment by quicklisp** [comment]
Had the same problem with dBodySetLinearVel and dCreateCylinder.

**Comment by BradWBeer** [comment]
Doh! Well, I fixed them too.
