### ISSUE TITLE
(defconstant null ...) breaks in development SBCL

### ISSUE THREAD

**Issue by quicklisp** [BradWBeer/clinch#48]
https://github.com/BradWBeer/CLinch/blob/master/freeimage/freeimage.lisp#L58 is triggering an error in SBCL due to the constraints of http://l1sp.org/cl/11.1.2.1.2 

http://report.quicklisp.org/2015-07-28/failure-report/clinch.html#freeimage has a full log.

**Comment by BradWBeer** [comment]
Removed the offending code. Strange it hasn't caused problems before. Try it again, it *should* build.

**Comment by quicklisp** [comment]
SBCL has been updated very recently (only in git so far) to detect more cases of 11.1.2.1.2 violations. I think this is a good thing, because if more than one project did (defconstant cl:null ...) the potential for clashes is high.

Your updates fixed things, thanks!

**Comment by BradWBeer** [comment]
No problems for a while.
